services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: us_mssql
    restart: no
    user: "0:0"
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}